from __future__ import annotations

import os
from typing import Any

from dotenv import load_dotenv
from openai import OpenAI

from backend.app.schemas.ai_decision import (
    AIVerificationDecision,
)


load_dotenv()


class FinanceVerificationAgent:
    """
    AI verification layer for FineOBS.

    The agent receives structured evidence generated by
    the deterministic reconciliation/matching system.
    It does not independently invent transaction facts.
    """

    def __init__(self) -> None:

        api_key = os.getenv("OPENAI_API_KEY")

        if not api_key:
            raise RuntimeError(
                "OPENAI_API_KEY is not configured."
            )

        self.client = OpenAI(
            api_key=api_key
        )

        self.model = os.getenv(
            "FINEOBS_AI_MODEL",
            "gpt-5.6-luna",
        )

    def _build_prompt(
        self,
        evidence: dict[str, Any],
    ) -> str:

        return f"""
You are the verification agent inside FineOBS,
an AI Finance Controller.

Your task is to verify a proposed financial reconciliation
using ONLY the supplied evidence.

Do not invent missing transaction information.

Do not assume that two records match merely because
their amounts are similar.

Financial safety rules:

1. AUTO_RECONCILE only when the evidence strongly supports
   the match and no material conflict exists.

2. HUMAN_REVIEW when the case is plausible but ambiguity
   or a financial discrepancy requires human approval.

3. UNRESOLVED when there is insufficient evidence to safely
   determine the correct outcome.

4. Never hide discrepancies.

5. Explain the decision using concrete evidence.

Return a structured decision.

Evidence:

{evidence}
"""

    def verify(
        self,
        evidence: dict[str, Any],
    ) -> AIVerificationDecision:

        prompt = self._build_prompt(
            evidence
        )

        response = self.client.responses.parse(
            model=self.model,
            input=[
                {
                    "role": "system",
                    "content": (
                        "You are a conservative financial "
                        "verification agent."
                    ),
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
            text_format=AIVerificationDecision,
        )

        parsed = response.output_parsed

        if parsed is None:
            raise RuntimeError(
                "AI verification returned no structured result."
            )

        return parsed